// week6/EmployeeRecordsManagementSystem/frontend/src/App.jsx
import { useEffect, useState } from "react";
import api from "./api";

function App() {
  const [employees, setEmployees] = useState([]);
  const [search, setSearch] = useState("");

  const [editingId, setEditingId] = useState(null);

  const [form, setForm] = useState({
    employeeId: "",
    firstName: "",
    lastName: "",
    email: "",
    department: "",
    position: "",
    salary: ""
  });

  const loadEmployees = async () => {
    try {
      const res = await api.get("/employees");
      setEmployees(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    loadEmployees();
  }, []);

  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  const resetForm = () => {
    setForm({
      employeeId: "",
      firstName: "",
      lastName: "",
      email: "",
      department: "",
      position: "",
      salary: ""
    });

    setEditingId(null);
  };

  const saveEmployee = async (e) => {
    e.preventDefault();

    try {
      if (editingId) {
        await api.put(`/employees/${editingId}`, {
          ...form,
          salary: Number(form.salary)
        });
      } else {
        await api.post("/employees", {
          ...form,
          salary: Number(form.salary)
        });
      }

      resetForm();
      loadEmployees();
    } catch (err) {
      console.error(err);
    }
  };

  const editEmployee = (employee) => {
    setEditingId(employee._id);

    setForm({
      employeeId: employee.employeeId,
      firstName: employee.firstName,
      lastName: employee.lastName,
      email: employee.email,
      department: employee.department,
      position: employee.position,
      salary: employee.salary
    });
  };

  const deleteEmployee = async (id) => {
    if (!window.confirm("Delete this employee?")) return;

    try {
      await api.delete(`/employees/${id}`);
      loadEmployees();
    } catch (err) {
      console.error(err);
    }
  };

  const filteredEmployees = employees.filter((emp) =>
    (
      emp.firstName +
      " " +
      emp.lastName +
      " " +
      emp.department +
      " " +
      emp.position +
      " " +
      emp.email
    )
      .toLowerCase()
      .includes(search.toLowerCase())
  );

  return (
    <div style={{ padding: "20px" }}>
      <h1>Employee Management System</h1>

      <form onSubmit={saveEmployee}>
        <input
          name="employeeId"
          placeholder="Employee ID"
          value={form.employeeId}
          onChange={handleChange}
        />

        <input
          name="firstName"
          placeholder="First Name"
          value={form.firstName}
          onChange={handleChange}
        />

        <input
          name="lastName"
          placeholder="Last Name"
          value={form.lastName}
          onChange={handleChange}
        />

        <input
          name="email"
          placeholder="Email"
          value={form.email}
          onChange={handleChange}
        />

        <input
          name="department"
          placeholder="Department"
          value={form.department}
          onChange={handleChange}
        />

        <input
          name="position"
          placeholder="Position"
          value={form.position}
          onChange={handleChange}
        />

        <input
          type="number"
          name="salary"
          placeholder="Salary"
          value={form.salary}
          onChange={handleChange}
        />

        <button type="submit">
          {editingId ? "Update Employee" : "Add Employee"}
        </button>
      </form>

      <br />

      <input
        type="text"
        placeholder="Search employee..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        style={{
          width: "300px",
          padding: "8px"
        }}
      />

      <hr />

      <table border="1" cellPadding="10">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th>Position</th>
            <th>Salary</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          {filteredEmployees.map((emp) => (
            <tr key={emp._id}>
              <td>{emp.employeeId}</td>
              <td>
                {emp.firstName} {emp.lastName}
              </td>
              <td>{emp.email}</td>
              <td>{emp.department}</td>
              <td>{emp.position}</td>
              <td>{emp.salary}</td>

              <td>
                <button onClick={() => editEmployee(emp)}>
                  Edit
                </button>

                <button
                  onClick={() => deleteEmployee(emp._id)}
                  style={{ marginLeft: "5px" }}
                >
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default App;

// week6/LibraryBookManagementSystem/frontend/src/App.vue
<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";

const API_URL = "http://localhost:5000/api/books";

const books = ref([]);

const bookId = ref("");
const title = ref("");
const author = ref("");
const category = ref("");

const editingId = ref(null);

// Fetch Books
const fetchBooks = async () => {
  try {
    const res = await axios.get(API_URL);
    books.value = res.data;
  } catch (err) {
    console.error(err);
  }
};

// Add or Update
const saveBook = async () => {
  try {
    const payload = {
      bookId: bookId.value,
      title: title.value,
      author: author.value,
      category: category.value,
    };

    if (editingId.value) {
      await axios.put(`${API_URL}/${editingId.value}`, payload);
      editingId.value = null;
    } else {
      await axios.post(API_URL, payload);
    }

    clearForm();
    fetchBooks();
  } catch (err) {
    console.error(err);
  }
};

// Edit
const editBook = (book) => {
  editingId.value = book._id;
  bookId.value = book.bookId;
  title.value = book.title;
  author.value = book.author;
  category.value = book.category;
};

// Delete
const deleteBook = async (id) => {
  if (!confirm("Delete this book?")) return;

  try {
    await axios.delete(`${API_URL}/${id}`);
    fetchBooks();
  } catch (err) {
    console.error(err);
  }
};

// Clear Form
const clearForm = () => {
  bookId.value = "";
  title.value = "";
  author.value = "";
  category.value = "";
};

onMounted(fetchBooks);
</script>

<template>
  <div class="container">
    <h1>📚 Library Book Management System</h1>

    <div class="form">
      <input v-model="bookId" placeholder="Book ID" />
      <input v-model="title" placeholder="Title" />
      <input v-model="author" placeholder="Author" />
      <input v-model="category" placeholder="Category" />

      <button @click="saveBook">
        {{ editingId ? "Update Book" : "Add Book" }}
      </button>
    </div>

    <h2>Books List</h2>

    <table>
      <thead>
        <tr>
          <th>Book ID</th>
          <th>Title</th>
          <th>Author</th>
          <th>Category</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <tr v-for="book in books" :key="book._id">
          <td>{{ book.bookId }}</td>
          <td>{{ book.title }}</td>
          <td>{{ book.author }}</td>
          <td>{{ book.category }}</td>

          <td>
            <button @click="editBook(book)">Edit</button>
            <button @click="deleteBook(book._id)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style>
body {
  font-family: Arial, sans-serif;
  background: #f4f4f4;
  margin: 0;
}

.container {
  width: 90%;
  margin: auto;
  padding: 20px;
}

h1 {
  text-align: center;
}

.form {
  display: grid;
  gap: 10px;
  margin-bottom: 20px;
}

input {
  padding: 10px;
}

button {
  padding: 10px;
  cursor: pointer;
}

table {
  width: 100%;
  background: white;
  border-collapse: collapse;
}

th,
td {
  border: 1px solid #ddd;
  padding: 10px;
  text-align: center;
}

th {
  background: #333;
  color: white;
}
</style>
